language: cpp

compiler:
  - clang

before_install:
  - sudo apt-get install clang git libssl-dev
  - sudo add-apt-repository -y ppa:boost-latest/ppa
  - sudo add-apt-repository -y ppa:kubuntu-ppa/backports
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -yqq
  - sudo apt-get install -y libboost1.55-dev libboost-system1.55-dev libboost-date-time1.55-dev libboost-random1.55-dev
  - sudo apt-get install -y cmake g++-4.8
  - sed -i -e 's/cmake_minimum_required(VERSION 3.1.0/cmake_minimum_required(VERSION 2.8.12/' ./CMakeLists.txt
script:
  - cmake -D CMAKE_CXX_FLAGS=-std=c++11 .
  - make
  - make install
